name: Fullstack CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-fontend:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install fontend dependencies
        run: npm install
        working-directory: ./fontend

      - name: Build fontend
        run: npm run build
        working-directory: ./fontend

      - name: Upload Cypress screenshots
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: ./cypress/screenshots

      - name: Upload Cypress videos
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: ./cypress/videos

  build-backend:
    runs-on: ubuntu-latest
    container:
      image: maven:3.9.2-eclipse-temurin-20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Kiểm tra thư mục backend có pom.xml
      - name: Check backend folder
        run: |
          ls backend
          pwd

      # Build backend
      - name: Build backend
        run: |
          cd backend
          mvn clean package

      # Upload file jar
      - name: Upload backend jar
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: backend/target/*.jar